### ISSUE TITLE
Release source of PDF

### ISSUE THREAD

**Issue by WebFreak001** [reyvaleza/vibed#1]
adding the source code for the PDF in this repository (even better if it's something text-based like LaTeX / Markdown) + images would make it possible to contribute to this book and keep evolving it.

**Comment by reyvaleza** [comment]
Thanks for responding and for your suggestion. I did not open this until now. I have the MS Word original doc. Will that be any good?

**Comment by WebFreak001** [comment]
any kind of source is good for starting

however you could save your word file e.g. as Word XML document, which would at least be more tracable in PRs (as you can read the changes on GitHub then)

I don't know how that works with images and stuff though.

**Comment by reyvaleza** [comment]
Thanks! I'll try.

**Comment by reyvaleza** [comment]
[BuildWebAppsInVibeD.docx](https://github.com/reyvaleza/vibed/files/6110940/BuildWebAppsInVibeD.docx)
The docx file

**Comment by reyvaleza** [comment]
I have shared to .docx file.
